spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:          - Path=/api/producto/**
#          - Header= token, \d+
#          - Method=GET,POST
#          - Query=color,verde
#          - Cookie=color,azul
        filters:          - StripPrefix=1
          - EjemploCookie=Hola mi mensaje personalizado, usuario, Mathew
      - id: servicio-items
        uri: lb://servicio-item
        predicates:
          - Path=/api/item/**
        filters:
          - StripPrefix=1
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 12345678
          - SetResponseHeader=Content-Type, text/plain
          - AddRequestParameter=nombre, Jared